version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
      - GENERIC_TIMEZONE=Europe/Madrid
      - N8N_EDITOR_BASE_URL=${TUNNEL_URL:-http://localhost:5678}
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: